required:
  - "apps"
  - "apps/backend"
  - "apps/frontend"
  - "apps/infrastructure"
  - "contracts"
  - "contracts/openapi"
  - "contracts/schemas"
  - "platform"
  - "platform/monitoring"
  - "scripts"
  - "docs"
  - "governance"
  - "ops-runbooks"
  - "product"
  - ".github/workflows"
  - "README.md"
  - "SECURITY.md"
  - "CODEOWNERS"