# terraform/vault-integration.tf
data "vault_generic_secret" "database" {
  path = "secret/techfactory/database"
}

data "vault_generic_secret" "api" {
  path = "secret/techfactory/api"
}

# Use of secrets inside ressources
resource "ovh_cloud_project_database_postgresql_user" "app_user" {
  service_name = ovh_cloud_project_database.postgresql.service_name
  cluster_id   = ovh_cloud_project_database.postgresql.id
  name         = data.vault_generic_secret.database.data["username"]
  # Password is generated by Vault
}

# Secured Outputs
output "vault_secrets_available" {
  value       = true
  description = "Tell if secrets Vault are accessibles"
  sensitive   = false
}