openapi: 3.1.0
info:
  title: Admin API
  version: "1.0.0"
  description: Administrative API (restricted)

paths:
  /admin/users:
    get:
      summary: List users
      security:
        - bearerAuth: []
      responses:
        "200":
          description: List of users